/* Live Supabase booking centre. No mock payment or local reservation state. */
(()=>{'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(n)/100);
const date=v=>new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kolkata'}).format(new Date(v));
const partner=new URLSearchParams(location.search).get('partner')==='1';
const labels={requested:'Request sent',offered:'Restaurant accepted · your turn',awaiting_payment:'Awaiting token payment',token_verified:'Token received · partner review',confirmed:'Booking confirmed',arrived:'Arrived',seated:'Seated',completed:'Completed',cancelled:'Cancelled',terms_accepted:'Terms accepted',preferences_confirmed:'Preferences acknowledged',review_submitted:'Verified review submitted',refunded:'Refund processed',hold_expired:'Hold expired',reminder_24h:'Your booking is within 24 hours',reminder_2h:'Your table is within 2 hours',table_available:'A table is available · request it now'};
const label=k=>labels[k]||(k.startsWith('running_late_')?`Running ${k.split('_').pop()} minutes late`:k);
let state={bookings:[],slots:[],restaurants:[],events:[],notices:[],reviews:[],members:[],wait:[],managedSlots:[]}, tab=partner?'Upcoming':'Find a table',busy=false,loading=false,submitDialog=null,refreshTimer,scanStream;
const tabs=partner?['Upcoming','Arrived','Seated','Completed','Cancelled','Availability','Updates']:['Find a table','My bookings','Waitlist','Updates'];
let filters={restaurant:'',date:'',party:2};
function toast(s){$('#message').textContent=s;}
async function rpc(name,args={}){const r=await window.sb.rpc(name,args);if(r.error)throw new Error(r.error.message);return r.data;}
async function query(table,order,limit=300){let q=window.sb.from(table).select('*');if(order)q=q.order(order,{ascending:false});const r=await q.limit(limit);if(r.error)throw new Error(r.error.message);return r.data;}
function restaurant(id){return state.restaurants.find(r=>r.id===id)?.name||'Restaurant';}
function button(text,action,id,extra=''){return `<button type="button" data-action="${action}" data-id="${esc(id)}" ${extra}>${esc(text)}</button>`;}
function summary(b){return `<dl><div><dt>Date & time (IST)</dt><dd>${date(b.starts_at)}</dd></div><div><dt>Guests</dt><dd>${b.party}</dd></div><div><dt>Agreed discount</dt><dd>${b.discount}% on eligible items</dd></div><div><dt>Minimum eligible bill</dt><dd>${money(b.min_bill_paise)}</dd></div><div><dt>Token ${b.paid_paise>0?'received':'required'}</dt><dd>${money(b.paid_paise||b.token_paise)}</dd></div></dl><p class="note">Your agreed discount applies to eligible items when the minimum bill is met. Any verified token paid is deducted from the amount due after discount.<br><strong>Exclusions:</strong> ${esc(b.exclusions)}</p><p class="dim">Cancel by ${date(b.cancel_before)} for a full token refund request. After this cutoff the token is non-refundable. A refund is only complete when its provider reference is verified.</p>`;}
function prefs(b){const p=b.preferences||{};return `<p>${esc([p.occasion,p.seating,p.dietary,p.high_chair?'High chair requested':''].filter(Boolean).join(' · ')||'No special requests')}</p><small>${b.preferences_confirmed?'Acknowledged by restaurant':'Preferences are requests; restaurant acknowledgement pending.'}</small>`;}
function bookingCard(b){const expired=b.expires_at&&new Date(b.expires_at)<=new Date();let actions='';
if(partner){if(!expired&&b.status==='requested')actions+=button('Accept · hold for 5 minutes','offer',b.id);if(b.status==='token_verified')actions+=button('Acknowledge token & confirm','confirm',b.id);if(b.status==='confirmed')actions+=button('Check in with QR / code','checkin',b.id);if(b.status==='arrived')actions+=button('Mark seated','seated',b.id);if(b.status==='seated')actions+=button('Complete visit','completed',b.id);if(!b.preferences_confirmed&&!['completed','cancelled'].includes(b.status))actions+=button('Acknowledge preferences','preferences',b.id);
}else{if(!expired&&b.status==='offered')actions+=button('Review & proceed','accept',b.id);if(b.status==='confirmed')actions+=button('Running late','late',b.id);if(b.status==='completed'&&!state.reviews.some(r=>r.booking_id===b.id))actions+=button('Review your visit','review',b.id);}
if(['requested','offered','awaiting_payment','token_verified','confirmed'].includes(b.status))actions+=button(partner?'Cancel reservation':'Decline / cancel','cancel',b.id,'class="danger"');
const events=state.events.filter(e=>e.booking_id===b.id).sort((a,c)=>a.id-c.id);
return `<article class="card ${b.status==='confirmed'?'confirmed':''}" id="booking-${esc(b.id)}"><span class="badge">${esc(expired?'Hold expired · updating':label(b.status))}</span><h2>${esc(restaurant(b.restaurant_id))}</h2><p class="code">Booking ID: ${esc(b.id)}</p>${b.expires_at&&!expired?`<p class="note">Held until ${date(b.expires_at)} · <span data-countdown="${esc(b.expires_at)}"></span></p>`:''}${summary(b)}${b.late_minutes?`<p class="note">Customer expects to arrive ${b.late_minutes} minutes late. Please contact the restaurant if plans change further.</p>`:''}${b.status==='awaiting_payment'?'<p class="note">Online token payments are not connected yet. No money has been charged and this booking is not confirmed.</p>':''}${b.status==='token_verified'?'<p class="note">Token amount verified. The restaurant must acknowledge receipt to confirm this booking.</p>':''}${b.status==='cancelled'?`<p>Reason: ${esc(b.cancellation_reason)}<br>Refund: ${esc(b.refund_status.replaceAll('_',' '))}${b.refund_paise?' · '+money(b.refund_paise):''}</p>`:''}<details><summary>Guest preferences</summary>${prefs(b)}</details><details><summary>Shared booking timeline (${events.length})</summary><ol class="timeline">${events.map(e=>`<li>${esc(label(e.kind))}<time>${date(e.created_at)}</time></li>`).join('')}</ol></details>${!partner&&b.status==='confirmed'?`<details><summary>Your arrival QR & check-in code</summary><canvas class="qr" data-qr="${esc(b.id)}" aria-label="Booking check-in QR code"></canvas><p class="code">${esc('dinevo1|'+b.id+'|'+b.checkin_code)}</p><p class="dim">Show this only to restaurant staff when you arrive.</p></details>`:''}${state.reviews.filter(r=>r.booking_id===b.id).map(r=>`<p class="note">Verified visit · ${r.rating}/5<br>${esc(r.body)}</p>`).join('')}<div class="actions">${actions}</div></article>`;}
function render(){ const expanded=[...document.querySelectorAll('article[id] details[open]')].map(d=>[d.closest('article').id,[...d.closest('article').querySelectorAll('details')].indexOf(d)]); $('#tabs').innerHTML=tabs.map(t=>button(t,'tab',t,`aria-current="${t===tab}"`)).join('');let html='';
if(tab==='Find a table'){
html=`<div class="filters"><label>Restaurant<select id="filter-rest"><option value="">All restaurants</option>${state.restaurants.map(r=>`<option value="${esc(r.id)}" ${r.id===filters.restaurant?'selected':''}>${esc(r.name)}</option>`).join('')}</select></label><label>Date (IST)<input id="filter-date" type="date" value="${esc(filters.date)}"></label><label>Guests<input id="filter-party" type="number" min="1" max="30" value="${filters.party}"></label></div>`;
const slots=state.slots.filter(s=>(!filters.restaurant||s.restaurant_id===filters.restaurant)&&(!filters.date||new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(new Date(s.starts_at))===filters.date));
html+=`<div class="grid">${slots.map(s=>`<article class="card"><span class="badge">${s.discount}% agreed discount</span><h2>${esc(s.restaurant)}</h2><p>${date(s.starts_at)}</p><p>${s.remaining} seats available · up to ${s.max_party} per group</p><p>Minimum eligible bill ${money(s.min_bill_paise)} · Token ${money(s.token_paise)}</p><p class="dim">${esc(s.exclusions)}</p>${filters.party<=s.max_party?(s.remaining>=filters.party?button('Request this table','request',s.id):button('Join waitlist','wait',s.id)):'<p>Choose a smaller group or another slot.</p>'}</article>`).join('')}</div>`;
if(!slots.length)html+='<div class="empty">No published slots match yet. Restaurant partners must publish availability before live bookings can be requested.</div>';
}else if(tab==='Updates'){html='<p class="dim">In-app reminders and waitlist alerts refresh automatically. A waitlist alert does not reserve a table.</p>'+state.notices.map(n=>`<article class="card"><span class="badge">${n.read_at?'Read':'New'}</span><h3>${esc(label(n.kind))}</h3><p>${date(n.created_at)}</p>${n.booking_id?`<p class="code">Booking ${esc(n.booking_id)}</p>${button('Open booking','open-booking',n.booking_id)}`:button('See available tables','tab','Find a table')}${!n.read_at?button('Mark read','read',n.id):''}</article>`).join('');if(!state.notices.length)html+='<div class="empty">Your booking updates will appear here.</div>';
}else if(tab==='Waitlist'){html=state.wait.map(w=>{const s=state.slots.find(s=>s.id===w.slot_id);return `<article class="card"><h3>${esc(s?.restaurant||'Waitlisted table')}</h3><p>${s?date(s.starts_at):'Slot no longer available'} · ${w.party} guests</p><p>${w.notified_at?'Availability alert sent. Check slots to request your table.':'We will notify you here if enough seats become available.'}</p>${button('View slots','tab','Find a table')}${button('Leave waitlist','unwait',w.slot_id)}</article>`;}).join('')||'<div class="empty">No waitlisted tables.</div>';
}else if(tab==='Availability'){html=state.members.length?`<p>Publish seats available to Dinevo customers. Each active request reserves its guest count until its hold expires.</p>${button('Publish a time slot','publish','')}<div class="grid">${state.managedSlots.map(s=>`<article class="card"><h3>${esc(restaurant(s.restaurant_id))}</h3><p>${date(s.starts_at)}</p><p>${s.capacity} seats · ${s.discount}% · Token ${money(s.token_paise)}</p>${s.open?button('Close new requests','close-slot',s.id):'<p>Closed for new requests</p>'}</article>`).join('')}</div>`:'<div class="empty">Partner access is awaiting restaurant ownership verification. Contact Dinevo with your restaurant name and registered account email. Choosing a restaurant never grants access to its bookings.</div>';
}else{let rows=state.bookings;if(partner){const statuses={Upcoming:['requested','offered','awaiting_payment','token_verified','confirmed'],Arrived:['arrived'],Seated:['seated'],Completed:['completed'],Cancelled:['cancelled']};rows=rows.filter(b=>statuses[tab]?.includes(b.status));}html=rows.map(bookingCard).join('')||`<div class="empty">${partner&&!state.members.length?'No verified restaurant membership yet. Restaurant access must be approved before you can manage bookings.':'No bookings in this section yet.'}</div>`;}
$('#content').innerHTML=html;expanded.forEach(([id,n])=>{const d=document.getElementById(id)?.querySelectorAll('details')[n];if(d)d.open=true;});document.querySelectorAll('[data-qr]').forEach(c=>{const b=state.bookings.find(b=>b.id===c.dataset.qr);window.QRCode.toCanvas(c,'dinevo1|'+b.id+'|'+b.checkin_code,{width:220,margin:2},e=>{if(e)c.replaceWith(document.createTextNode('Use the check-in code below.'));});});tick();}
async function refresh(){if(loading||busy)return;loading=true;try{const [bookings,slots,restaurants,events,notices,reviews,members,wait]=await Promise.all([query('d2_bookings','starts_at'),rpc('d2_available'),query('d2_restaurants'),query('d2_events','id',1500),query('d2_notices','id'),query('d2_reviews'),query('d2_members'),query('d2_waitlist')]);const previous=new Map(state.bookings.map(b=>[b.id,b.status]));const managedSlots=partner&&members.length?(await query('d2_slots','starts_at')).filter(s=>members.some(m=>m.restaurant_id===s.restaurant_id)):[];state={bookings:partner?bookings.filter(b=>members.some(m=>m.restaurant_id===b.restaurant_id)):bookings.filter(b=>b.customer_id===dinevoAuth.getUser().id),slots,restaurants,events,notices,reviews,members,wait,managedSlots};if(!$('#dialog').open&& !document.activeElement?.matches('#content input,#content select,#content textarea'))render();const newlyConfirmed=state.bookings.find(b=>b.status==='confirmed'&&previous.has(b.id)&&previous.get(b.id)!=='confirmed');if(newlyConfirmed&&!$('#dialog').open)celebrate(newlyConfirmed); }catch(e){toast('Could not refresh: '+e.message);}finally{loading=false;}}
function modal(title,body,submit,fn){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;$('#dialog-submit').textContent=submit;$('#dialog-submit').hidden=!fn;$('#dialog-error').textContent='';submitDialog=fn;$('#dialog').showModal();}
function celebrate(b){modal(partner?'A new booking is confirmed':'See you at the table!',`<div class="celebrate"><div class="spark">✦</div><h2>${esc(restaurant(b.restaurant_id))}</h2><p>${date(b.starts_at)} · ${b.party} guests</p><p>${partner?'Find this booking in Upcoming, ready for arrival.':'Your booking is confirmed. Your QR code is ready in My bookings.'}</p></div>`,'OK',async()=>{});}
function stopScan(){scanStream?.getTracks().forEach(t=>t.stop());scanStream=null;}
$('#dialog').addEventListener('close',stopScan);$('#close-dialog').onclick=()=>{if(!busy)$('#dialog').close();};$('#dialog').addEventListener('cancel',e=>{if(busy)e.preventDefault();});
$('#dialog-form').onsubmit=async e=>{e.preventDefault();if(busy||!submitDialog)return;busy=true;$('#dialog-submit').disabled=true;try{await submitDialog(new FormData(e.target));$('#dialog').close();toast('Saved. Your booking information is up to date.');}catch(err){$('#dialog-error').textContent=err.message;}finally{busy=false;$('#dialog-submit').disabled=false;await refresh();render();}};
const input=(name,title,type='text',attrs='')=>`<label>${title}<input name="${name}" type="${type}" ${attrs}></label>`;
async function act(action,id){const b=state.bookings.find(b=>b.id===id),s=state.slots.find(s=>s.id===id);
if(action==='tab'){tab=id;render();return;}if(action==='open-booking'){tab=partner?({arrived:'Arrived',seated:'Seated',completed:'Completed',cancelled:'Cancelled'}[b?.status]||'Upcoming'):'My bookings';render();document.getElementById('booking-'+id)?.scrollIntoView({behavior:'smooth'});return;}
if(action==='request'){modal('Make it your kind of evening',`<p>${esc(s.restaurant)} · ${date(s.starts_at)} · ${filters.party} guests</p>${input('occasion','Occasion','text','maxlength="80" placeholder="Birthday, anniversary…"')}${input('seating','Seating preference','text','maxlength="80" placeholder="Indoor, outdoor, quiet corner…"')}<label>Dietary needs<textarea name="dietary" maxlength="500" placeholder="Tell the restaurant about allergies or dietary needs"></textarea></label><label><input type="checkbox" name="high_chair"> High chair requested</label><p class="note">Requests are subject to restaurant acknowledgement. ${s.discount}% on eligible items, minimum bill ${money(s.min_bill_paise)}. Token ${money(s.token_paise)}. ${esc(s.exclusions)}</p>${s.token_paise>0?'<p>Token payments are not connected yet; this slot cannot be fully confirmed online.</p>':''}`,'Send request',async f=>{await rpc('d2_request',{p_slot:id,p_party:filters.party,p_preferences:{occasion:f.get('occasion'),seating:f.get('seating'),dietary:f.get('dietary'),high_chair:f.has('high_chair')}});tab='My bookings';});return;}
if(action==='accept'){modal('Review your booking',summary(b)+prefs(b)+'<label><input type="checkbox" required> I reviewed the date, guests, discount and cancellation terms.</label>',b.token_paise?'Accept terms · payment pending':'Confirm booking',async()=>{await rpc('d2_action',{p_booking:id,p_action:'accept'});});return;}
if(action==='cancel'){const reasons=partner?['Restaurant unavailable','Date or time does not suit','Booked by mistake']:['Plans changed','Date or time does not suit','Discount does not suit','Chose another restaurant','Booked by mistake'];modal('Cancel this reservation?',`<p>${date(b.starts_at)} · ${esc(restaurant(b.restaurant_id))}</p><p>${b.paid_paise?((partner||Date.now()<=Date.parse(b.cancel_before))?'A full token refund will be requested. It is not refunded until confirmed by the provider.':'The cancellation cutoff has passed. Your token is non-refundable.'):'No token has been collected.'}</p><label>Reason<select name="reason" required><option value="">Select a reason</option>${reasons.map(r=>`<option>${r}</option>`).join('')}</select></label>`,'Confirm cancellation',f=>rpc('d2_action',{p_booking:id,p_action:'cancel',p_value:f.get('reason')}));return;}
if(action==='late'){modal('Let the restaurant know','<label>How late?<select name="minutes">'+[5,10,15,20,30].map(n=>`<option value="${n}">${n} minutes</option>`).join('')+'</select></label><p>This sends an in-app update. It does not extend your reservation automatically.</p>','Send update',f=>rpc('d2_action',{p_booking:id,p_action:'late',p_value:f.get('minutes')}));return;}
if(action==='review'){modal('How was your visit?','<p>Only completed bookings can leave a verified review.</p><label>Rating<select name="rating">'+[5,4,3,2,1].map(n=>`<option>${n}</option>`).join('')+'</select></label><label>Your review<textarea name="body" required maxlength="1000"></textarea></label>','Submit review',f=>rpc('d2_review',{p_booking:id,p_rating:Number(f.get('rating')),p_body:f.get('body')}));return;}
if(action==='checkin'){modal('Check in your guest',input('code','Paste the guest’s check-in code','text','required autocomplete="off"')+'<button type="button" id="scan">Scan QR with camera</button><video id="scan-video" muted playsinline style="width:100%;max-height:240px" hidden></video><p id="scan-help">Check-in is available from 2 hours before until 6 hours after the booking.</p>','Verify & mark arrived',f=>{const parts=String(f.get('code')).trim().split('|');if(parts.length!==3||parts[0]!=='dinevo1'||parts[1]!==id)throw new Error('This code belongs to a different booking or is invalid.');return rpc('d2_checkin',{p_booking:id,p_code:parts[2]});});$('#scan').onclick=async()=>{try{if(!window.BarcodeDetector)throw new Error('Camera QR scanning is unavailable in this browser. Paste the guest’s code instead.');const detector=new BarcodeDetector({formats:['qr_code']});scanStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});const v=$('#scan-video');v.hidden=false;v.srcObject=scanStream;await v.play();const scan=async()=>{if(!scanStream)return;try{const codes=await detector.detect(v);if(codes[0]){$('[name=code]').value=codes[0].rawValue;stopScan();$('#scan-help').textContent='Code scanned. Verify to check in.';return;}}catch{}setTimeout(scan,400);};scan();}catch(e){$('#scan-help').textContent=e.message;}};return;}
if(action==='publish'){modal('Publish table availability',`<label>Restaurant<select name="restaurant">${state.members.map(m=>`<option value="${esc(m.restaurant_id)}">${esc(restaurant(m.restaurant_id))}</option>`).join('')}</select></label>${input('start','Date and time (IST)','datetime-local','required')}${input('capacity','Total seats available','number','required min="1" max="500" value="10"')}${input('max','Maximum guests per booking','number','required min="1" max="30" value="6"')}${input('discount','Agreed discount (%)','number','required min="0" max="100" value="20"')}${input('minimum','Minimum eligible bill (₹)','number','required min="0" step="0.01" value="1000"')}${input('cancel','Cancellation cutoff (hours before arrival)','number','required min="0" max="720" value="24"')}<label>Discount exclusions<textarea name="exclusions" required maxlength="2000">Cold drinks and other items excluded in the restaurant’s terms are not eligible for the discount.</textarea></label><p class="note">These slots require no token while online payments are being connected. The customer confirms after you accept their request.</p>`,'Publish slot',f=>rpc('d2_publish_slot',{p_restaurant:f.get('restaurant'),p_start:new Date(f.get('start')+':00+05:30').toISOString(),p_capacity:Number(f.get('capacity')),p_max_party:Number(f.get('max')),p_discount:Number(f.get('discount')),p_min_bill:Math.round(Number(f.get('minimum'))*100),p_token:0,p_cancel_hours:Number(f.get('cancel')),p_exclusions:f.get('exclusions')}));return;}
if(['offer','confirm','seated','completed','preferences'].includes(action)){modal(label(action)||action,`<p>${esc(restaurant(b.restaurant_id))} · ${date(b.starts_at)}</p>${action==='confirm'?summary(b):''}<p>${{offer:'Accept this request and give the customer five minutes to confirm.',confirm:'Confirm receipt of the verified token and secure this table.',seated:'Mark this party as seated.',completed:'Finish this visit and enable the customer’s verified review.',preferences:'Acknowledge that you have reviewed the customer’s preferences.'}[action]}</p>`,'Confirm',()=>rpc('d2_action',{p_booking:id,p_action:action}));return;}
busy=true;try{if(action==='wait'||action==='unwait')await rpc('d2_wait',{p_slot:id,p_party:filters.party,p_join:action==='wait'});else if(action==='read')await rpc('d2_read_notice',{p_id:Number(id)});else if(action==='close-slot')await rpc('d2_close_slot',{p_slot:id});toast('Saved.');}finally{busy=false;}await refresh();render();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&!busy)act(b.dataset.action,b.dataset.id).catch(e=>toast(e.message));});
document.addEventListener('change',e=>{if(e.target.id==='filter-rest')filters.restaurant=e.target.value;else if(e.target.id==='filter-date')filters.date=e.target.value;else if(e.target.id==='filter-party')filters.party=Math.max(1,Math.min(30,Number(e.target.value)||2));else return;render();});
function tick(){document.querySelectorAll('[data-countdown]').forEach(e=>{const n=Math.max(0,Math.ceil((Date.parse(e.dataset.countdown)-Date.now())/1000));e.textContent=n?`${Math.floor(n/60)}m ${n%60}s remaining`:'Hold expired';});}
if(partner){$('#title').textContent='Every guest. Every detail.';$('#intro').textContent='Your service board, from the first request to the final thank you.';$('#switch').textContent='Customer bookings';$('#switch').href='booking-centre.html';}
dinevoAuth.init(partner?'Partner':'Bookings', '✦');dinevoAuth.ready.then(async()=>{await refresh();render();refreshTimer=setInterval(()=>{if(!document.hidden)refresh();},15000);setInterval(tick,1000);});window.addEventListener('pagehide',()=>{clearInterval(refreshTimer);stopScan();});
})();
